# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: 12 inci di belakang kamera
subtitle: Foto bagus ditentukan dimana kita berdiri
email: endy@muhardin.com
description: > # this means to ignore newlines until "baseurl:"
  Tulisan seputar pernak pernik fotografi, teknik lighting, bisnis fotografi
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://rana.endy.muhardin.com" 
twitter_username: endymuhardin
github_username:  endymuhardin

permalink: /:categories/:title/
paginate: 10
recent_posts: 5
excerpt_link: "Read on &rarr;"
titlecase: true

# Google Analytics
google_analytics_tracking_id: UA-36102948-1

# Facebook Like
facebook_like: true

# Facebook Comments
facebook_appid: 269506799827290

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock


